using Forge.Domain.Constants;
using MuscleGroupEnum = Forge.Domain.Enums.MuscleGroup;

namespace Forge.Infrastructure.Seeding;

public static class ExerciseCatalog
{
    public static IReadOnlyCollection<ExerciseSeedDefinition> All { get; } =
    [
        Exercise("chest-supino-reto", "Supino reto", "Empurrada horizontal com barra para peitoral.", MuscleGroupIds.Chest, MuscleGroupEnum.Chest, "Barra", 1001),
        Exercise("chest-supino-inclinado", "Supino inclinado", "Empurrada inclinada para a porção superior do peitoral.", MuscleGroupIds.Chest, MuscleGroupEnum.Chest, "Barra", 1002),
        Exercise("chest-supino-declinado", "Supino declinado", "Empurrada em banco declinado para ênfase inferior do peitoral.", MuscleGroupIds.Chest, MuscleGroupEnum.Chest, "Barra", 1003),
        Exercise("chest-supino-halteres", "Supino com halteres", "Empurrada horizontal com maior amplitude de movimento.", MuscleGroupIds.Chest, MuscleGroupEnum.Chest, "Halteres", 1004),
        Exercise("chest-crucifixo-halteres", "Crucifixo com halteres", "Adução horizontal para isolamento do peitoral.", MuscleGroupIds.Chest, MuscleGroupEnum.Chest, "Halteres", 1005),
        Exercise("chest-crucifixo-cabo", "Crucifixo no cabo", "Adução horizontal com tensão contínua no peitoral.", MuscleGroupIds.Chest, MuscleGroupEnum.Chest, "Cabo", 1006),
        Exercise("chest-crossover", "Crossover", "Movimento de fechamento no cabo para peitoral.", MuscleGroupIds.Chest, MuscleGroupEnum.Chest, "Cabo", 1007),
        Exercise("chest-paralelas-peito", "Paralelas com foco em peito", "Empurrada vertical com inclinação do tronco para peitoral.", MuscleGroupIds.Chest, MuscleGroupEnum.Chest, "Peso corporal", 1008),
        Exercise("chest-flexao-bracos", "Flexão de braços", "Empurrada com peso corporal para peitoral e tríceps.", MuscleGroupIds.Chest, MuscleGroupEnum.Chest, "Peso corporal", 1009),
        Exercise("chest-peck-deck", "Peck deck", "Adução guiada para isolamento do peitoral.", MuscleGroupIds.Chest, MuscleGroupEnum.Chest, "Máquina", 1010),

        Exercise("back-puxada-frente", "Puxada pela frente", "Puxada vertical para dorsais.", MuscleGroupIds.Back, MuscleGroupEnum.Back, "Polia", 2001),
        Exercise("back-barra-fixa", "Barra fixa", "Puxada vertical com peso corporal para costas.", MuscleGroupIds.Back, MuscleGroupEnum.Back, "Peso corporal", 2002),
        Exercise("back-remada-curvada", "Remada curvada", "Remada livre para dorsais e parte média das costas.", MuscleGroupIds.Back, MuscleGroupEnum.Back, "Barra", 2003),
        Exercise("back-remada-serrote", "Remada unilateral com halter", "Remada unilateral para dorsais.", MuscleGroupIds.Back, MuscleGroupEnum.Back, "Halter", 2004),
        Exercise("back-remada-baixa", "Remada baixa", "Remada sentada com cabo para costas.", MuscleGroupIds.Back, MuscleGroupEnum.Back, "Cabo", 2005),
        Exercise("back-remada-cavalinho", "Remada cavalinho", "Remada com apoio para dorsais e romboides.", MuscleGroupIds.Back, MuscleGroupEnum.Back, "Barra", 2006),
        Exercise("back-pulldown-bracos-retos", "Pulldown com braços retos", "Extensão de ombros no cabo para dorsais.", MuscleGroupIds.Back, MuscleGroupEnum.Back, "Cabo", 2007),
        Exercise("back-remada-maquina", "Remada na máquina", "Remada guiada para costas.", MuscleGroupIds.Back, MuscleGroupEnum.Back, "Máquina", 2008),
        Exercise("back-puxada-triangulo", "Puxada com triângulo", "Puxada vertical com pegada neutra.", MuscleGroupIds.Back, MuscleGroupEnum.Back, "Polia", 2009),
        Exercise("back-puxada-supinada", "Puxada supinada", "Puxada vertical com pegada supinada.", MuscleGroupIds.Back, MuscleGroupEnum.Back, "Polia", 2010),

        Exercise("shoulders-desenvolvimento-barra", "Desenvolvimento com barra", "Empurrada vertical para ombros.", MuscleGroupIds.Shoulders, MuscleGroupEnum.Shoulders, "Barra", 3001),
        Exercise("shoulders-desenvolvimento-halteres", "Desenvolvimento com halteres", "Empurrada vertical com halteres para deltoides.", MuscleGroupIds.Shoulders, MuscleGroupEnum.Shoulders, "Halteres", 3002),
        Exercise("shoulders-elevacao-lateral", "Elevação lateral", "Abdução de ombros para deltoide medial.", MuscleGroupIds.Shoulders, MuscleGroupEnum.Shoulders, "Halteres", 3003),
        Exercise("shoulders-elevacao-frontal", "Elevação frontal", "Flexão de ombros para deltoide anterior.", MuscleGroupIds.Shoulders, MuscleGroupEnum.Shoulders, "Halteres", 3004),
        Exercise("shoulders-crucifixo-inverso", "Crucifixo inverso", "Abdução horizontal para deltoide posterior.", MuscleGroupIds.Shoulders, MuscleGroupEnum.Shoulders, "Halteres", 3005),
        Exercise("shoulders-face-pull", "Face pull", "Puxada para deltoide posterior e estabilidade escapular.", MuscleGroupIds.Shoulders, MuscleGroupEnum.Shoulders, "Cabo", 3006),
        Exercise("shoulders-arnold-press", "Desenvolvimento Arnold", "Empurrada vertical com rotação dos ombros.", MuscleGroupIds.Shoulders, MuscleGroupEnum.Shoulders, "Halteres", 3007),
        Exercise("shoulders-remada-alta", "Remada alta", "Puxada vertical para deltoides e trapézio.", MuscleGroupIds.Shoulders, MuscleGroupEnum.Shoulders, "Barra", 3008),
        Exercise("shoulders-elevacao-lateral-cabo", "Elevação lateral no cabo", "Elevação lateral com tensão contínua.", MuscleGroupIds.Shoulders, MuscleGroupEnum.Shoulders, "Cabo", 3009),
        Exercise("shoulders-desenvolvimento-maquina", "Desenvolvimento na máquina", "Empurrada guiada para ombros.", MuscleGroupIds.Shoulders, MuscleGroupEnum.Shoulders, "Máquina", 3010),

        Exercise("biceps-rosca-direta", "Rosca direta", "Flexão de cotovelos com barra para bíceps.", MuscleGroupIds.Biceps, MuscleGroupEnum.Arms, "Barra", 4001),
        Exercise("biceps-rosca-alternada", "Rosca alternada", "Flexão alternada de cotovelos com halteres.", MuscleGroupIds.Biceps, MuscleGroupEnum.Arms, "Halteres", 4002),
        Exercise("biceps-rosca-martelo", "Rosca martelo", "Flexão com pegada neutra para bíceps e braquial.", MuscleGroupIds.Biceps, MuscleGroupEnum.Arms, "Halteres", 4003),
        Exercise("biceps-rosca-scott", "Rosca Scott", "Flexão de cotovelos com apoio para isolamento.", MuscleGroupIds.Biceps, MuscleGroupEnum.Arms, "Banco Scott", 4004),
        Exercise("biceps-rosca-concentrada", "Rosca concentrada", "Flexão unilateral com foco em controle.", MuscleGroupIds.Biceps, MuscleGroupEnum.Arms, "Halter", 4005),
        Exercise("biceps-rosca-cabo", "Rosca no cabo", "Flexão de cotovelos com tensão contínua.", MuscleGroupIds.Biceps, MuscleGroupEnum.Arms, "Cabo", 4006),
        Exercise("biceps-rosca-inclinada", "Rosca inclinada", "Flexão com ombros estendidos para alongar o bíceps.", MuscleGroupIds.Biceps, MuscleGroupEnum.Arms, "Halteres", 4007),
        Exercise("biceps-rosca-21", "Rosca 21", "Série combinada com amplitudes parciais e completa.", MuscleGroupIds.Biceps, MuscleGroupEnum.Arms, "Barra", 4008),
        Exercise("biceps-rosca-arremesso-polias", "Rosca nas polias altas", "Flexão bilateral em cabo alto para bíceps.", MuscleGroupIds.Biceps, MuscleGroupEnum.Arms, "Cabo", 4009),
        Exercise("biceps-rosca-maquina", "Rosca na máquina", "Flexão guiada para bíceps.", MuscleGroupIds.Biceps, MuscleGroupEnum.Arms, "Máquina", 4010),

        Exercise("triceps-pulley-corda", "Tríceps pulley com corda", "Extensão de cotovelos na polia com corda.", MuscleGroupIds.Triceps, MuscleGroupEnum.Arms, "Cabo", 5001),
        Exercise("triceps-pulley-barra", "Tríceps pulley com barra", "Extensão de cotovelos na polia com barra.", MuscleGroupIds.Triceps, MuscleGroupEnum.Arms, "Cabo", 5002),
        Exercise("triceps-testa", "Tríceps testa", "Extensão de cotovelos deitado com barra.", MuscleGroupIds.Triceps, MuscleGroupEnum.Arms, "Barra", 5003),
        Exercise("triceps-frances", "Tríceps francês", "Extensão acima da cabeça para tríceps.", MuscleGroupIds.Triceps, MuscleGroupEnum.Arms, "Halter", 5004),
        Exercise("triceps-banco", "Mergulho no banco", "Extensão de cotovelos com apoio em banco.", MuscleGroupIds.Triceps, MuscleGroupEnum.Arms, "Peso corporal", 5005),
        Exercise("triceps-paralelas", "Paralelas com foco em tríceps", "Empurrada em paralelas com tronco mais vertical.", MuscleGroupIds.Triceps, MuscleGroupEnum.Arms, "Peso corporal", 5006),
        Exercise("triceps-coice", "Coice de tríceps", "Extensão unilateral de cotovelo com halter.", MuscleGroupIds.Triceps, MuscleGroupEnum.Arms, "Halter", 5007),
        Exercise("triceps-supino-fechado", "Supino fechado", "Empurrada com pegada fechada para tríceps.", MuscleGroupIds.Triceps, MuscleGroupEnum.Arms, "Barra", 5008),
        Exercise("triceps-extensao-cabo-unilateral", "Extensão unilateral no cabo", "Extensão de cotovelo unilateral na polia.", MuscleGroupIds.Triceps, MuscleGroupEnum.Arms, "Cabo", 5009),
        Exercise("triceps-maquina", "Tríceps na máquina", "Extensão guiada para tríceps.", MuscleGroupIds.Triceps, MuscleGroupEnum.Arms, "Máquina", 5010),

        Exercise("forearms-rosca-punho", "Rosca de punho", "Flexão de punhos para antebraços.", MuscleGroupIds.Forearms, MuscleGroupEnum.Arms, "Barra", 6001),
        Exercise("forearms-rosca-punho-inversa", "Rosca de punho inversa", "Extensão de punhos para antebraços.", MuscleGroupIds.Forearms, MuscleGroupEnum.Arms, "Barra", 6002),
        Exercise("forearms-rosca-inversa", "Rosca inversa", "Flexão de cotovelos pronada para braquiorradial.", MuscleGroupIds.Forearms, MuscleGroupEnum.Arms, "Barra", 6003),
        Exercise("forearms-farmer-walk", "Caminhada do fazendeiro", "Carregada pesada para pegada e antebraços.", MuscleGroupIds.Forearms, MuscleGroupEnum.Arms, "Halteres", 6004),
        Exercise("forearms-pronacao", "Pronação de antebraço", "Rotação pronada controlada para antebraço.", MuscleGroupIds.Forearms, MuscleGroupEnum.Arms, "Halter", 6005),
        Exercise("forearms-supinacao", "Supinação de antebraço", "Rotação supinada controlada para antebraço.", MuscleGroupIds.Forearms, MuscleGroupEnum.Arms, "Halter", 6006),
        Exercise("forearms-pinca-anilhas", "Pinça com anilhas", "Sustentação em pinça para força de pegada.", MuscleGroupIds.Forearms, MuscleGroupEnum.Arms, "Anilhas", 6007),
        Exercise("forearms-hang-barra", "Sustentação na barra", "Suspensão na barra para resistência de pegada.", MuscleGroupIds.Forearms, MuscleGroupEnum.Arms, "Barra fixa", 6008),
        Exercise("forearms-roller", "Enrolador de punho", "Flexão e extensão com rolo para antebraços.", MuscleGroupIds.Forearms, MuscleGroupEnum.Arms, "Rolo de punho", 6009),
        Exercise("forearms-grip", "Apertador de mão", "Compressão repetida para força de pegada.", MuscleGroupIds.Forearms, MuscleGroupEnum.Arms, "Grip", 6010),

        Exercise("core-prancha", "Prancha", "Isometria para estabilidade do core.", MuscleGroupIds.Core, MuscleGroupEnum.Core, "Peso corporal", 7001),
        Exercise("core-abdominal-crunch", "Abdominal crunch", "Flexão de tronco para reto abdominal.", MuscleGroupIds.Core, MuscleGroupEnum.Core, "Peso corporal", 7002),
        Exercise("core-elevacao-pernas", "Elevação de pernas", "Flexão de quadril com foco em abdômen inferior.", MuscleGroupIds.Core, MuscleGroupEnum.Core, "Peso corporal", 7003),
        Exercise("core-abdominal-bicicleta", "Abdominal bicicleta", "Flexão e rotação alternada para oblíquos.", MuscleGroupIds.Core, MuscleGroupEnum.Core, "Peso corporal", 7004),
        Exercise("core-prancha-lateral", "Prancha lateral", "Isometria lateral para oblíquos.", MuscleGroupIds.Core, MuscleGroupEnum.Core, "Peso corporal", 7005),
        Exercise("core-russian-twist", "Giro russo", "Rotação de tronco para oblíquos.", MuscleGroupIds.Core, MuscleGroupEnum.Core, "Anilha", 7006),
        Exercise("core-abdominal-cabo", "Abdominal no cabo", "Flexão de tronco ajoelhado na polia.", MuscleGroupIds.Core, MuscleGroupEnum.Core, "Cabo", 7007),
        Exercise("core-dead-bug", "Dead bug", "Controle lombopélvico alternado.", MuscleGroupIds.Core, MuscleGroupEnum.Core, "Peso corporal", 7008),
        Exercise("core-mountain-climber", "Mountain climber", "Estabilidade do core com movimento alternado.", MuscleGroupIds.Core, MuscleGroupEnum.Core, "Peso corporal", 7009),
        Exercise("core-ab-wheel", "Roda abdominal", "Extensão anti-flexão para core.", MuscleGroupIds.Core, MuscleGroupEnum.Core, "Roda abdominal", 7010),

        Exercise("lowerback-levantamento-terra", "Levantamento terra", "Extensão de quadril e tronco para cadeia posterior.", MuscleGroupIds.LowerBack, MuscleGroupEnum.Back, "Barra", 8001),
        Exercise("lowerback-hiperextensao", "Hiperextensão lombar", "Extensão de tronco no banco romano.", MuscleGroupIds.LowerBack, MuscleGroupEnum.Back, "Banco romano", 8002),
        Exercise("lowerback-good-morning", "Good morning", "Hinge de quadril com barra para lombar e posteriores.", MuscleGroupIds.LowerBack, MuscleGroupEnum.Back, "Barra", 8003),
        Exercise("lowerback-superman", "Superman", "Extensão lombar no solo.", MuscleGroupIds.LowerBack, MuscleGroupEnum.Back, "Peso corporal", 8004),
        Exercise("lowerback-pull-through", "Pull-through no cabo", "Extensão de quadril no cabo para cadeia posterior.", MuscleGroupIds.LowerBack, MuscleGroupEnum.Back, "Cabo", 8005),
        Exercise("lowerback-terra-romeno", "Terra romeno", "Hinge com joelhos semi-flexionados para posteriores e lombar.", MuscleGroupIds.LowerBack, MuscleGroupEnum.Back, "Barra", 8006),
        Exercise("lowerback-bird-dog", "Bird dog", "Estabilidade lombar alternando braço e perna.", MuscleGroupIds.LowerBack, MuscleGroupEnum.Back, "Peso corporal", 8007),
        Exercise("lowerback-extensao-maquina", "Extensão lombar na máquina", "Extensão guiada para lombar.", MuscleGroupIds.LowerBack, MuscleGroupEnum.Back, "Máquina", 8008),
        Exercise("lowerback-terra-sumo", "Levantamento terra sumo", "Terra com base ampla para cadeia posterior.", MuscleGroupIds.LowerBack, MuscleGroupEnum.Back, "Barra", 8009),
        Exercise("lowerback-prancha-reversa", "Prancha reversa", "Isometria posterior para lombar e glúteos.", MuscleGroupIds.LowerBack, MuscleGroupEnum.Back, "Peso corporal", 8010),

        Exercise("glutes-elevacao-pelvica", "Elevação pélvica", "Extensão de quadril com apoio para glúteos.", MuscleGroupIds.Glutes, MuscleGroupEnum.Glutes, "Barra", 9001),
        Exercise("glutes-ponte-gluteos", "Ponte de glúteos", "Extensão de quadril no solo.", MuscleGroupIds.Glutes, MuscleGroupEnum.Glutes, "Peso corporal", 9002),
        Exercise("glutes-afundo", "Afundo", "Passada unilateral com ênfase em glúteos e pernas.", MuscleGroupIds.Glutes, MuscleGroupEnum.Glutes, "Halteres", 9003),
        Exercise("glutes-passada", "Passada caminhando", "Avanço alternado para glúteos e pernas.", MuscleGroupIds.Glutes, MuscleGroupEnum.Glutes, "Halteres", 9004),
        Exercise("glutes-coice-cabo", "Coice no cabo", "Extensão unilateral de quadril na polia.", MuscleGroupIds.Glutes, MuscleGroupEnum.Glutes, "Cabo", 9005),
        Exercise("glutes-abducao-maquina", "Abdução na máquina", "Afastamento de quadris para glúteo médio.", MuscleGroupIds.Glutes, MuscleGroupEnum.Glutes, "Máquina", 9006),
        Exercise("glutes-step-up", "Subida no banco", "Subida unilateral para glúteos e quadríceps.", MuscleGroupIds.Glutes, MuscleGroupEnum.Glutes, "Banco", 9007),
        Exercise("glutes-agachamento-sumo", "Agachamento sumô", "Agachamento com base ampla para glúteos e adutores.", MuscleGroupIds.Glutes, MuscleGroupEnum.Glutes, "Halter", 9008),
        Exercise("glutes-kickback-maquina", "Coice na máquina", "Extensão guiada de quadril para glúteos.", MuscleGroupIds.Glutes, MuscleGroupEnum.Glutes, "Máquina", 9009),
        Exercise("glutes-abducao-elastico", "Abdução com elástico", "Abdução de quadril com resistência elástica.", MuscleGroupIds.Glutes, MuscleGroupEnum.Glutes, "Elástico", 9010),

        Exercise("quadriceps-agachamento-livre", "Agachamento livre", "Agachamento com barra para quadríceps e cadeia inferior.", MuscleGroupIds.Quadriceps, MuscleGroupEnum.Legs, "Barra", 10001),
        Exercise("quadriceps-leg-press", "Leg press", "Empurrada de pernas na plataforma.", MuscleGroupIds.Quadriceps, MuscleGroupEnum.Legs, "Máquina", 10002),
        Exercise("quadriceps-cadeira-extensora", "Cadeira extensora", "Extensão de joelhos para isolamento de quadríceps.", MuscleGroupIds.Quadriceps, MuscleGroupEnum.Legs, "Máquina", 10003),
        Exercise("quadriceps-agachamento-frontal", "Agachamento frontal", "Agachamento com barra à frente para quadríceps.", MuscleGroupIds.Quadriceps, MuscleGroupEnum.Legs, "Barra", 10004),
        Exercise("quadriceps-hack", "Agachamento hack", "Agachamento guiado com ênfase em quadríceps.", MuscleGroupIds.Quadriceps, MuscleGroupEnum.Legs, "Máquina", 10005),
        Exercise("quadriceps-passada-bulgara", "Agachamento búlgaro", "Agachamento unilateral com pé elevado.", MuscleGroupIds.Quadriceps, MuscleGroupEnum.Legs, "Halteres", 10006),
        Exercise("quadriceps-avanco", "Avanço", "Passo à frente unilateral para quadríceps e glúteos.", MuscleGroupIds.Quadriceps, MuscleGroupEnum.Legs, "Halteres", 10007),
        Exercise("quadriceps-sissy-squat", "Sissy squat", "Agachamento com grande ênfase no quadríceps.", MuscleGroupIds.Quadriceps, MuscleGroupEnum.Legs, "Peso corporal", 10008),
        Exercise("quadriceps-agachamento-goblet", "Agachamento goblet", "Agachamento segurando halter ou kettlebell.", MuscleGroupIds.Quadriceps, MuscleGroupEnum.Legs, "Halter", 10009),
        Exercise("quadriceps-smith", "Agachamento no Smith", "Agachamento guiado no Smith.", MuscleGroupIds.Quadriceps, MuscleGroupEnum.Legs, "Smith", 10010),

        Exercise("hamstrings-mesa-flexora", "Mesa flexora", "Flexão de joelhos deitado para posteriores.", MuscleGroupIds.Hamstrings, MuscleGroupEnum.Legs, "Máquina", 11001),
        Exercise("hamstrings-cadeira-flexora", "Cadeira flexora", "Flexão de joelhos sentado para posteriores.", MuscleGroupIds.Hamstrings, MuscleGroupEnum.Legs, "Máquina", 11002),
        Exercise("hamstrings-stiff", "Stiff", "Hinge de quadril para posteriores.", MuscleGroupIds.Hamstrings, MuscleGroupEnum.Legs, "Barra", 11003),
        Exercise("hamstrings-terra-romeno-halteres", "Terra romeno com halteres", "Hinge com halteres para posteriores.", MuscleGroupIds.Hamstrings, MuscleGroupEnum.Legs, "Halteres", 11004),
        Exercise("hamstrings-flexora-unilateral", "Flexora unilateral", "Flexão de joelho unilateral para posteriores.", MuscleGroupIds.Hamstrings, MuscleGroupEnum.Legs, "Máquina", 11005),
        Exercise("hamstrings-nordic-curl", "Nordic curl", "Flexão nórdica para posteriores.", MuscleGroupIds.Hamstrings, MuscleGroupEnum.Legs, "Peso corporal", 11006),
        Exercise("hamstrings-good-morning", "Good morning para posteriores", "Hinge com barra enfatizando posteriores.", MuscleGroupIds.Hamstrings, MuscleGroupEnum.Legs, "Barra", 11007),
        Exercise("hamstrings-glute-ham-raise", "Glute ham raise", "Flexão de joelho e extensão de quadril.", MuscleGroupIds.Hamstrings, MuscleGroupEnum.Legs, "Banco GHD", 11008),
        Exercise("hamstrings-flexora-bola", "Flexora na bola", "Flexão de joelhos com bola suíça.", MuscleGroupIds.Hamstrings, MuscleGroupEnum.Legs, "Bola suíça", 11009),
        Exercise("hamstrings-pull-through", "Pull-through para posteriores", "Hinge no cabo para posteriores e glúteos.", MuscleGroupIds.Hamstrings, MuscleGroupEnum.Legs, "Cabo", 11010),

        Exercise("calves-gemeos-em-pe", "Gêmeos em pé", "Flexão plantar em pé para panturrilhas.", MuscleGroupIds.Calves, MuscleGroupEnum.Legs, "Máquina", 12001),
        Exercise("calves-gemeos-sentado", "Gêmeos sentado", "Flexão plantar sentado com ênfase no sóleo.", MuscleGroupIds.Calves, MuscleGroupEnum.Legs, "Máquina", 12002),
        Exercise("calves-panturrilha-leg-press", "Panturrilha no leg press", "Flexão plantar na plataforma do leg press.", MuscleGroupIds.Calves, MuscleGroupEnum.Legs, "Máquina", 12003),
        Exercise("calves-panturrilha-unilateral", "Panturrilha unilateral", "Flexão plantar unilateral para controle e amplitude.", MuscleGroupIds.Calves, MuscleGroupEnum.Legs, "Peso corporal", 12004),
        Exercise("calves-panturrilha-smith", "Panturrilha no Smith", "Flexão plantar em pé guiada.", MuscleGroupIds.Calves, MuscleGroupEnum.Legs, "Smith", 12005),
        Exercise("calves-panturrilha-degrau", "Panturrilha no degrau", "Flexão plantar com amplitude em degrau.", MuscleGroupIds.Calves, MuscleGroupEnum.Legs, "Peso corporal", 12006),
        Exercise("calves-donkey-calf", "Panturrilha donkey", "Flexão plantar com tronco inclinado.", MuscleGroupIds.Calves, MuscleGroupEnum.Legs, "Máquina", 12007),
        Exercise("calves-tibial-anterior", "Elevação tibial", "Dorsiflexão para tibial anterior.", MuscleGroupIds.Calves, MuscleGroupEnum.Legs, "Peso corporal", 12008),
        Exercise("calves-panturrilha-hack", "Panturrilha no hack", "Flexão plantar apoiado no hack.", MuscleGroupIds.Calves, MuscleGroupEnum.Legs, "Máquina", 12009),
        Exercise("calves-saltos-baixos", "Saltos baixos", "Saltos curtos para potência e resistência de panturrilhas.", MuscleGroupIds.Calves, MuscleGroupEnum.Legs, "Peso corporal", 12010),

        Exercise("fullbody-burpee", "Burpee", "Movimento completo combinando agachamento, prancha e salto.", MuscleGroupIds.FullBody, MuscleGroupEnum.FullBody, "Peso corporal", 13001),
        Exercise("fullbody-thruster", "Thruster", "Agachamento frontal com desenvolvimento acima da cabeça.", MuscleGroupIds.FullBody, MuscleGroupEnum.FullBody, "Halteres", 13002),
        Exercise("fullbody-clean-press", "Clean and press", "Levantamento do solo ao ombro seguido de empurrada.", MuscleGroupIds.FullBody, MuscleGroupEnum.FullBody, "Barra", 13003),
        Exercise("fullbody-kettlebell-swing", "Swing com kettlebell", "Hinge explosivo com kettlebell.", MuscleGroupIds.FullBody, MuscleGroupEnum.FullBody, "Kettlebell", 13004),
        Exercise("fullbody-agachamento-desenvolvimento", "Agachamento com desenvolvimento", "Agachamento seguido de empurrada vertical.", MuscleGroupIds.FullBody, MuscleGroupEnum.FullBody, "Halteres", 13005),
        Exercise("fullbody-renegade-row", "Remada renegada", "Prancha com remada alternada.", MuscleGroupIds.FullBody, MuscleGroupEnum.FullBody, "Halteres", 13006),
        Exercise("fullbody-snatch-halter", "Snatch com halter", "Arranco unilateral do solo acima da cabeça.", MuscleGroupIds.FullBody, MuscleGroupEnum.FullBody, "Halter", 13007),
        Exercise("fullbody-man-maker", "Man maker", "Sequência com flexão, remada, agachamento e desenvolvimento.", MuscleGroupIds.FullBody, MuscleGroupEnum.FullBody, "Halteres", 13008),
        Exercise("fullbody-corda-naval", "Corda naval", "Ondulações com corda para corpo inteiro.", MuscleGroupIds.FullBody, MuscleGroupEnum.FullBody, "Corda naval", 13009),
        Exercise("fullbody-sled-push", "Empurrada de trenó", "Empurrada pesada para corpo inteiro.", MuscleGroupIds.FullBody, MuscleGroupEnum.FullBody, "Trenó", 13010),

        Exercise("cardio-corrida-esteira", "Corrida na esteira", "Corrida controlada para condicionamento cardiovascular.", MuscleGroupIds.Cardio, MuscleGroupEnum.Cardio, "Esteira", 14001),
        Exercise("cardio-bicicleta-ergometrica", "Bicicleta ergométrica", "Pedalada estacionária para condicionamento.", MuscleGroupIds.Cardio, MuscleGroupEnum.Cardio, "Bicicleta", 14002),
        Exercise("cardio-eliptico", "Elíptico", "Movimento contínuo de baixo impacto.", MuscleGroupIds.Cardio, MuscleGroupEnum.Cardio, "Elíptico", 14003),
        Exercise("cardio-remo-ergometro", "Remo ergômetro", "Remada contínua para condicionamento.", MuscleGroupIds.Cardio, MuscleGroupEnum.Cardio, "Remo", 14004),
        Exercise("cardio-escada", "Simulador de escada", "Subida contínua para condicionamento.", MuscleGroupIds.Cardio, MuscleGroupEnum.Cardio, "Máquina", 14005),
        Exercise("cardio-pular-corda", "Pular corda", "Saltos ritmados para cardio e coordenação.", MuscleGroupIds.Cardio, MuscleGroupEnum.Cardio, "Corda", 14006),
        Exercise("cardio-hiit-bike", "HIIT na bicicleta", "Intervalos de alta intensidade na bicicleta.", MuscleGroupIds.Cardio, MuscleGroupEnum.Cardio, "Bicicleta", 14007),
        Exercise("cardio-caminhada-inclinada", "Caminhada inclinada", "Caminhada em inclinação para cardio.", MuscleGroupIds.Cardio, MuscleGroupEnum.Cardio, "Esteira", 14008),
        Exercise("cardio-air-bike", "Air bike", "Pedalada com braços e pernas em alta intensidade.", MuscleGroupIds.Cardio, MuscleGroupEnum.Cardio, "Air bike", 14009),
        Exercise("cardio-polichinelo", "Polichinelo", "Salto coordenado para aquecimento e cardio.", MuscleGroupIds.Cardio, MuscleGroupEnum.Cardio, "Peso corporal", 14010),

        Exercise("other-mobilidade-quadril", "Mobilidade de quadril", "Sequência de mobilidade para preparar o quadril.", MuscleGroupIds.Other, MuscleGroupEnum.Other, "Peso corporal", 15001),
        Exercise("other-alongamento-peitoral", "Alongamento de peitoral", "Alongamento estático para peitoral.", MuscleGroupIds.Other, MuscleGroupEnum.Other, "Peso corporal", 15002),
        Exercise("other-alongamento-dorsal", "Alongamento dorsal", "Alongamento para dorsais e coluna torácica.", MuscleGroupIds.Other, MuscleGroupEnum.Other, "Peso corporal", 15003),
        Exercise("other-mobilidade-tornozelo", "Mobilidade de tornozelo", "Exercício de mobilidade para amplitude do tornozelo.", MuscleGroupIds.Other, MuscleGroupEnum.Other, "Peso corporal", 15004),
        Exercise("other-rotacao-toracica", "Rotação torácica", "Mobilidade de coluna torácica em rotação.", MuscleGroupIds.Other, MuscleGroupEnum.Other, "Peso corporal", 15005),
        Exercise("other-ativacao-escapular", "Ativação escapular", "Controle de escápulas para preparação de membros superiores.", MuscleGroupIds.Other, MuscleGroupEnum.Other, "Elástico", 15006),
        Exercise("other-caminhada-lateral-elastico", "Caminhada lateral com elástico", "Ativação de quadril e glúteo médio.", MuscleGroupIds.Other, MuscleGroupEnum.Other, "Elástico", 15007),
        Exercise("other-aquecimento-articular", "Aquecimento articular", "Rotina geral para preparar articulações.", MuscleGroupIds.Other, MuscleGroupEnum.Other, "Peso corporal", 15008),
        Exercise("other-liberacao-miofascial", "Liberação miofascial", "Auto-massagem com rolo para recuperação.", MuscleGroupIds.Other, MuscleGroupEnum.Other, "Rolo", 15009),
        Exercise("other-respiracao-diafragmatica", "Respiração diafragmática", "Controle respiratório para recuperação e estabilidade.", MuscleGroupIds.Other, MuscleGroupEnum.Other, "Peso corporal", 15010)
    ];

    private static ExerciseSeedDefinition Exercise(
        string key,
        string name,
        string description,
        Guid muscleGroupId,
        MuscleGroupEnum legacyMuscleGroup,
        string? equipment,
        int displayOrder)
    {
        return new ExerciseSeedDefinition(
            OfficialExerciseIds.FromCatalogKey(key),
            name,
            description,
            muscleGroupId,
            legacyMuscleGroup,
            equipment,
            displayOrder);
    }
}
